[stack]
  id = "com.microsoft.oryx.stack"
  build-image = "mcr.microsoft.com/oryx/pack-stack-base"
  run-image =	"mcr.microsoft.com/oryx/pack-stack-base"

[[buildpacks]]
  id = "com.microsoft.oryx.buildpack"
  uri = "oryx-buildpack"

[[groups]]
  [[groups.buildpacks]]
    id = "com.microsoft.oryx.buildpack"
    version = "0.0.1"
